export { type CreateDatabaseOptions, createDatabase, type Database } from "./client.ts";
export {
  createEmbeddingIndex,
  createEmbeddingTable,
  type EmbeddingCounts,
  type EmbeddingModelRow,
  embeddingCounts,
  embeddingIndexExists,
  ensureItemEmbeddings,
  insertEmbeddings,
  itemEmbeddingsDimension,
  itemEmbeddingsExists,
  type PendingItem,
  pendingEmbeddingItems,
  readEmbeddingModel,
  rebuildItemEmbeddings,
  recordEmbeddingFailure,
  retryBackoffSeconds,
  writeEmbeddingModel,
} from "./embeddings.ts";
export {
  createInterestClusters,
  type ExplorationOptions,
  explorationCandidates,
  type InterestCluster,
  interestClustersExists,
  type ProfileSummary,
  parseVectorLiteral,
  readProfileSummary,
  rebuildInterestClusters,
  type ScoredItem,
  type ScoreOptions,
  type SignalledItem,
  scoreItems,
  signalCount,
  signalledItems,
  writeInterestProfile,
} from "./interest.ts";
export { type MigrationResult, migrate } from "./migrate.ts";
export {
  DEFAULT_USER_ID,
  embeddingFailures,
  embeddingModel,
  type ItemRow,
  type ItemStateRow,
  itemSources,
  itemState,
  items,
  type NewItemRow,
  type NewSourceRow,
  type SourceRow,
  sources,
  users,
} from "./schema.ts";
export {
  DEFAULT_MAX_DISTANCE,
  hybridSearch,
  type SearchFilters,
  type SearchHit,
  type SearchOptions,
  type SearchResult,
  textScores,
} from "./search.ts";
